# Generated by Django 4.2.7 on 2023-11-20 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('des', models.CharField(max_length=100)),
                ('prize', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(upload_to='product/images')),
            ],
        ),
    ]
